Updated the main ReadME file with a small description of the web app …
ArslanYM/StarterHive pull request #41
Opened 2023-05-22 13:32 UTC by Shoetan

Closes:https://github.com/ArslanYM/StarterHive/issues/39

Updated the main ReadME file with a small description of the web app and a Link that leads to the web app directory.

Before:
![Screenshot from 2023-05-22 14-09-24](https://github.com/ArslanYM/StarterHive/assets/17912134/1031c75f-e664-493a-abca-918dfe3518e3)

After:
![Screenshot from 2023-05-22 14-09-50](https://github.com/ArslanYM/StarterHive/assets/17912134/fb23ed68-0b1d-41cc-87b9-237e616f0ae3)

2023-05-22 13:52 UTC, ArslanYM commented on README.md
> +StarterHive is an open source project that helps global new developers in contributing to beginner friendly issues.Accelerating skills dvelopment,
This line would definitely need some changes. You can use CHATGPT to rephrase the sentences in a better way.

2023-05-22 13:52 UTC, ArslanYM commented on README.md
> +paving the way for inclusive open-source contribtion worldwide.
These changes dont imply what the project is.

2023-05-22 13:53 UTC, ArslanYM requested changes
Definitely needs some rephrasing.  And clear cut description of the project

2023-05-22 20:03 UTC, Shoetan commented
@ArslanYM Thank you so much for your feedback and guidance. I sincerely appreciate it. Regarding the changes, you would need, I need some more clarification on what the project is all about. From what I can gather StarterHive helps by eliminating the boring task of manually searching through repositories and looking for issues to solve.

2023-05-23 04:58 UTC, ArslanYM commented
@Shoetan yes thats right. Starter Hive helps you find issues in projects or codebases which are run my companies/organisations that hire people remotely.

2023-05-24 04:35 UTC, Shoetan commented
@ArslanYM Thank you once again for your patience and guidance. I have just made the changes you requested to close this issue.

2023-05-24 05:00 UTC, ArslanYM commented
This PR has conflicts with the main branch, maybe because you didnt pull the updated changes. Sorry to say but this PR is closeworthy. Thankyou for your contribution

2023-05-24 05:00 UTC, closed without merging